export interface WorldState {
  worldAlpha: number;
  worldBeta: number;
  worldGamma: number;
  averageSpeed: number;
  averageLocalDensity: number;
  activeBonds: number;
  activeRelationshipEntities: number;
  averageRelationshipAge: number;
  averageCoherence: number;
  activeHigherOrderInteractions: number;
  spatiallyActiveRelationships: number;
  influenceActiveRelationships: number;
  dualActiveRelationships: number;
  influenceOnlyRelationships: number;
  averageSynergy: number;
  averageFieldPotential: number;
  maximumFieldPotential: number;
  averageFieldGradient: number;
  maximumFieldGradient: number;
  initialEntities: number;
  externalArrivals: number;
  reproductionBirths: number;
  eligibleReproductiveRelationships: number;
  birthsLast10000Ticks: number;
  totalReproductionEvents: number;
  relationshipsCreated: number;
  relationshipsDestroyed: number;
  dormantRelationships: number;
  dimensionalTransitions: number;
  lastReproductionTick: number | null;
  lastExternalArrivalTick: number | null;
  totalRuptureEvents: number;
  rupturesLast10000Ticks: number;
  lastRuptureTick: number | null;
  currentlyQualifiedRuptureCandidates: number;
  ticks: number;
  simulationTime: number;
}
