import assert from "node:assert/strict";
import test from "node:test";
import { createBranchAuthority } from "../src/counterfactual/branchAuthority.js";
import { buildComparisonFrame, entityCausalKeys, relationshipCausalKey } from "../src/counterfactual/correspondence.js";
import { compareBranch, emptyMilestones } from "../src/counterfactual/divergence.js";
import { COUNTERFACTUAL_IMPULSE_PRESETS, COUNTERFACTUAL_MAXIMUM_DISPLACEMENT, COUNTERFACTUAL_MAXIMUM_IMPULSE, applyIntervention, interventionHash, resolveCanonicalCluster, validateIntervention } from "../src/counterfactual/intervention.js";
import { COUNTERFACTUAL_INTERVENTION_VERSION, COUNTERFACTUAL_LIMITS, type CounterfactualIntervention } from "../src/counterfactual/types.js";
import { branchResourceLimitReason } from "../src/counterfactual/resources.js";
import { CounterfactualTargetGate } from "../src/counterfactual/scheduling.js";
import { DEFAULT_COUNTERFACTUAL_APPEARANCE, validateCounterfactualAppearance } from "../src/counterfactual/appearance.js";
import { PRIMARY_TRAIL_LIMITS, PrimaryLiveTrailRecorder } from "../src/rendering/liveTrails.js";
import { CounterfactualTrailStore } from "../src/rendering/counterfactualTrails.js";
import type { BranchFrame } from "../src/counterfactual/types.js";
import { COUNTERFACTUAL_POKE_MULTIPLIERS, MAXIMUM_PRESET_EFFECTIVE_IMPULSE, effectiveImpulse, effectiveImpulseText } from "../src/counterfactual/pokePresentation.js";
import { deterministicStateHash } from "../src/simulation/deterministicStateHash.js";
import type { Entity } from "../src/simulation/entity.js";
import { Universe } from "../src/simulation/universe.js";
import { validateContinuation } from "../src/simulation/saveState.js";

const advance=(u:Universe,n:number)=>{for(let i=0;i<n;i++)u.step();};
const intervention=(entityId:number=0,x:number=COUNTERFACTUAL_IMPULSE_PRESETS.moderate,y:number=0):CounterfactualIntervention=>({schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"entity-impulse",target:{entityId},deltaVelocity:{x,y}});

test("branch origin hash equals capture and creation leaves every primary continuation field unchanged",()=>{
  const primary=new Universe("counterfactual-isolation");advance(primary,250);const before=primary.continuationState(),hash=deterministicStateHash(before),branch=createBranchAuthority("B-0001",before,intervention());
  assert.equal(branch.metadata.originStateHash,hash);assert.equal(deterministicStateHash(primary.continuationState()),hash);advance(branch.universe,100);
  assert.equal(deterministicStateHash(primary.continuationState()),hash,"branch stepping cannot touch primary state, PRNG, occurrences, relationships, or laws");assert.notEqual(deterministicStateHash(branch.universe.continuationState()),hash);
});

test("intervention mutates branch velocity fields only and consumes no PRNG",()=>{
  const primary=new Universe("counterfactual-fields"),captured=primary.continuationState(),created=createBranchAuthority("B-0001",captured,intervention(2,.01,-.02)),after=created.universe.continuationState();
  assert.equal(after.randomState,captured.randomState);assert.equal(primary.continuationState().randomState,captured.randomState);assert.equal(after.entities[2].vx,captured.entities[2].vx+.01);assert.equal(after.entities[2].vy,captured.entities[2].vy-.02);
  after.entities[2].vx=captured.entities[2].vx;after.entities[2].vy=captured.entities[2].vy;assert.deepEqual(after,captured);
});

test("impulse presets, multipliers, effective display, and validation bounds are explicit",()=>{
  assert.deepEqual(COUNTERFACTUAL_IMPULSE_PRESETS,{subtle:.025,moderate:.075,strong:.175});assert.deepEqual(COUNTERFACTUAL_POKE_MULTIPLIERS,[1,2,5,10,20]);assert.equal(MAXIMUM_PRESET_EFFECTIVE_IMPULSE,3.5);assert.equal(COUNTERFACTUAL_MAXIMUM_IMPULSE,4);for(const value of Object.values(COUNTERFACTUAL_IMPULSE_PRESETS))assert.doesNotThrow(()=>validateIntervention(intervention(0,value,0)));assert.doesNotThrow(()=>validateIntervention(intervention(0,3.5,0)));
  assert.equal(effectiveImpulse(.075,5),.375);assert.equal(effectiveImpulseText("Moderate",.075,5),"Moderate 0.075 × 5\nEffective impulse: 0.375 world-units/tick");
  for(const delta of [{x:0,y:0},{x:4.001,y:0},{x:3,y:3},{x:Number.NaN,y:0}])assert.throws(()=>validateIntervention(intervention(0,delta.x,delta.y)));
  const invalid:CounterfactualIntervention={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"cluster-impulse",target:{anchorEntityId:1,resolvedEntityIds:[1,0]},deltaVelocity:{x:.005,y:0}};assert.throws(()=>validateIntervention(invalid),/sorted/);
});

test("canonical one-hop cluster is stable and frozen in numeric order",()=>{
  const universe=new Universe("optimization-v1-benchmark");advance(universe,5_000);const relationship=[...universe.relationshipLayer.entities.values()][0];assert.ok(relationship);
  const first=resolveCanonicalCluster(universe,relationship.parentAId),continuation=universe.continuationState();continuation.relationships.reverse();const restored=new Universe(universe.seed,continuation),second=resolveCanonicalCluster(restored,relationship.parentAId);
  assert.deepEqual(second,first);assert.deepEqual(first,[...first].sort((a,b)=>a-b));assert.ok(first.includes(relationship.parentBId));
});

test("same parent and intervention have golden identity and identical replay hashes",()=>{
  const primary=new Universe("counterfactual-golden");advance(primary,100);const captured=primary.continuationState(),a=createBranchAuthority("B-0001",captured,intervention()),b=createBranchAuthority("B-display-name",captured,intervention());
  assert.equal(a.metadata.branchCausalId,b.metadata.branchCausalId);assert.equal(a.metadata.postInterventionStateHash,b.metadata.postInterventionStateHash);assert.equal(interventionHash(intervention()),"aeff41eda8acb00860abce555437c59e2fffd5a1c3e686f41ff096d0c3b52a67");
  const hashesA:string[]=[],hashesB:string[]=[];for(let i=0;i<200;i++){a.universe.step();b.universe.step();if(i%25===0){hashesA.push(deterministicStateHash(a.universe.continuationState()));hashesB.push(deterministicStateHash(b.universe.continuationState()));}}assert.deepEqual(hashesA,hashesB);
});

test("pause/catch-up and comparison cadence cannot change branch trajectory",()=>{
  const primary=new Universe("counterfactual-cadence"),captured=primary.continuationState(),a=createBranchAuthority("B-1",captured,intervention()).universe,b=createBranchAuthority("B-2",captured,intervention()).universe;advance(a,300);advance(b,100);advance(b,200);
  assert.equal(deterministicStateHash(a.continuationState()),deterministicStateHash(b.continuationState()));const context={originStateHash:deterministicStateHash(captured),originEntityCount:captured.entities.length};buildComparisonFrame(a,context);buildComparisonFrame(a,context);assert.equal(deterministicStateHash(a.continuationState()),deterministicStateHash(b.continuationState()));
});

test("causal correspondence does not align divergent descendants by array index",()=>{
  const origin=new Universe("counterfactual-correspondence"),captured=origin.continuationState(),originHash=deterministicStateHash(captured),make=(fingerprint:string)=>{const state=structuredClone(captured),base=structuredClone(state.entities[0]) as Entity;state.entities.push({...base,creationIndex:state.entities.length,creationTimestamp:5,origin:"reproduction",birthTick:5,parentEntityIds:[0,1],parentRelationshipId:"local-any",fingerprint} as Entity);return new Universe(state.universe,state);};
  const a=make("a".repeat(64)),b=make("b".repeat(64)),context={originStateHash:originHash,originEntityCount:captured.entities.length},keysA=entityCausalKeys(a,context),keysB=entityCausalKeys(b,context);assert.equal(keysA.get(0),keysB.get(0));assert.notEqual(keysA.get(captured.entities.length),keysB.get(captured.entities.length));assert.equal(relationshipCausalKey(keysA.get(0)!,keysA.get(1)!),relationshipCausalKey(keysA.get(1)!,keysA.get(0)!));
  const frame=compareBranch(a,buildComparisonFrame(b,context),context,"B",0,emptyMilestones(),"RUNNING",0);assert.ok(frame.entities.some((x)=>x.correspondence==="branch-only"));
});

test("branch owns Law Evolution and crossing an epoch cannot mutate primary manifest",()=>{
  const primary=new Universe("counterfactual-law",undefined,{lawEpochInterval:25});advance(primary,24);const captured=primary.continuationState(),primaryManifest=structuredClone(primary.lawEvolution.activeManifest),created=createBranchAuthority("B-law",captured,intervention());assert.deepEqual(created.universe.lawEvolution.activeManifest,primaryManifest);assert.notStrictEqual(created.universe.lawEvolution.activeManifest,primary.lawEvolution.activeManifest);advance(created.universe,2);assert.deepEqual(primary.lawEvolution.activeManifest,primaryManifest);assert.equal(created.universe.lawEvolution.completedEpoch,1);assert.equal(primary.lawEvolution.completedEpoch,0);
});

test("v1 is resource-governed with no tick-age cap",()=>{assert.equal(COUNTERFACTUAL_LIMITS.maximumPopulation,1_000);assert.equal(COUNTERFACTUAL_LIMITS.maximumRelationships,10_000);assert.equal("maximumAge" in COUNTERFACTUAL_LIMITS,false);assert.match(branchResourceLimitReason(1_001,0,0)!,/population/);assert.match(branchResourceLimitReason(1,10_001,0)!,/relationship/);assert.match(branchResourceLimitReason(1,1,COUNTERFACTUAL_LIMITS.hardMemoryBytes+1)!,/memory/);assert.equal(branchResourceLimitReason(1_000,10_000,COUNTERFACTUAL_LIMITS.hardMemoryBytes),null);});

test("counterfactual faculties remain outside continuation and explicitly closed in Laboratory",async()=>{const universe=new Universe("counterfactual-boundary"),keys=Object.keys(universe.continuationState());assert.ok(!keys.some((key)=>/branch|counterfactual/i.test(key)));const lab=await import("node:fs/promises").then((fs)=>fs.readFile("server/laboratory/laboratoryMcpServer.ts","utf8"));for(const name of ["counterfactual_create","counterfactual_status","counterfactual_compare","counterfactual_inspect","counterfactual_terminate"])assert.match(lab,new RegExp(`${name}:false`));});

test("v2 displacement changes branch position only and preserves primary and PRNG",()=>{for(const kind of ["entity-displace","cluster-displace"] as const){const primary=new Universe(`displace-${kind}`),captured=primary.continuationState(),hash=deterministicStateHash(captured),target=kind==="entity-displace"?{entityId:0}:{anchorEntityId:0,resolvedEntityIds:[0]},value={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind,target,deltaPosition:{x:12,y:-7}} as CounterfactualIntervention,branch=createBranchAuthority("B",captured,value).universe.continuationState();assert.equal(branch.randomState,captured.randomState);assert.equal(branch.entities[0].x,captured.entities[0].x+12);assert.equal(branch.entities[0].y,captured.entities[0].y-7);assert.equal(branch.entities[0].vx,captured.entities[0].vx);assert.equal(branch.entities[0].vy,captured.entities[0].vy);assert.equal(deterministicStateHash(primary.continuationState()),hash);}assert.throws(()=>validateIntervention({schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"entity-displace",target:{entityId:0},deltaPosition:{x:COUNTERFACTUAL_MAXIMUM_DISPLACEMENT+1,y:0}}));});

test("radial and spin vectors use a canonical order-independent center",()=>{const primary=new Universe("optimization-v1-benchmark");advance(primary,5000);const rel=[...primary.relationshipLayer.entities.values()][0]!,anchor=rel.parentAId,members=resolveCanonicalCluster(primary,anchor),captured=primary.continuationState(),center=members.reduce((s,id)=>({x:s.x+captured.entities[id].x/members.length,y:s.y+captured.entities[id].y/members.length}),{x:0,y:0});for(const [kind,extra] of [["cluster-radial-pulse",{mode:"expand"}],["cluster-spin",{direction:"clockwise"}]] as const){const value={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind,target:{anchorEntityId:anchor,resolvedEntityIds:members},magnitude:.2,...extra} as CounterfactualIntervention,a=createBranchAuthority("A",captured,value),b=createBranchAuthority("B",structuredClone(captured),value);assert.equal(a.metadata.postInterventionStateHash,b.metadata.postInterventionStateHash);assert.equal(a.universe.continuationState().randomState,captured.randomState);const id=members.find(id=>Math.hypot(captured.entities[id].x-center.x,captured.entities[id].y-center.y)>0)!;const dx=captured.entities[id].x-center.x,dy=captured.entities[id].y-center.y,len=Math.hypot(dx,dy),dvx=a.universe.entities[id].vx-captured.entities[id].vx,dvy=a.universe.entities[id].vy-captured.entities[id].vy;if(kind==="cluster-radial-pulse")assert.ok(Math.abs(dvx-dx/len*.2)<1e-12&&Math.abs(dvy-dy/len*.2)<1e-12);else assert.ok(Math.abs(dvx-dy/len*.2)<1e-12&&Math.abs(dvy+dx/len*.2)<1e-12);} });

test("relationship sever is atomic, continuation-valid, branch-only, and PRNG-free",()=>{const primary=new Universe("optimization-v1-benchmark");advance(primary,5000);const relation=[...primary.relationshipLayer.entities.values()][0]!;assert.ok(relation);const captured=primary.continuationState(),hash=deterministicStateHash(captured),value={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"relationship-sever",target:{relationshipId:relation.id}} as CounterfactualIntervention,branch=createBranchAuthority("B",captured,value).universe;assert.equal(branch.relationshipLayer.entities.has(relation.id),false);assert.equal(branch.bonds.has(relation.id),false);assert.equal(branch.continuationState().randomState,captured.randomState);assert.ok(primary.relationshipLayer.entities.has(relation.id));assert.equal(deterministicStateHash(primary.continuationState()),hash);assert.doesNotThrow(()=>validateContinuation(branch.continuationState()));});

test("all v2 intervention encodings are canonical and presentation-free",()=>{const a={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"entity-impulse",target:{entityId:0},deltaVelocity:{x:.3,y:.4}} as CounterfactualIntervention,b={deltaVelocity:{y:.4,x:.3},target:{entityId:0},kind:"entity-impulse",schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION} as CounterfactualIntervention;assert.equal(interventionHash(a),interventionHash(b));assert.doesNotMatch(JSON.stringify(a),/preset|multiplier/);const u=new Universe("v2-prng"),before=u.continuationState().randomState;applyIntervention(u,validateIntervention(a,u));assert.equal(u.continuationState().randomState,before);});

test("overlay target backpressure preserves one equal-tick comparison frame per accepted target",()=>{const gate=new CounterfactualTargetGate();assert.equal(gate.canPublish(),true);gate.markPublished();assert.equal(gate.canPublish(),false,"a newer primary snapshot cannot replace the in-flight target");gate.markFrameReceived();assert.equal(gate.canPublish(),true);gate.markPublished();gate.reset();assert.equal(gate.canPublish(),true);});

test("default branch appearance is subtle warm ember and presentation values are bounded only",()=>{const style=DEFAULT_COUNTERFACTUAL_APPEARANCE;assert.ok(style.hue>=10&&style.hue<=35);assert.ok(style.overlayOpacity<=.55&&style.entitySize<=1&&style.relationshipOpacity<.5);assert.equal(style.preset,"ember");const customized=validateCounterfactualAppearance({...style,hue:999,trailSamples:999});assert.equal(customized.hue,359);assert.equal(customized.trailSamples,32);const universe=new Universe("appearance-causality"),hash=deterministicStateHash(universe.continuationState());validateCounterfactualAppearance(customized);assert.equal(deterministicStateHash(universe.continuationState()),hash);});

test("stronger impulse remains branch-only and leaves the primary deterministic hash unchanged",()=>{const primary=new Universe("stronger-branch-only"),captured=primary.continuationState(),hash=deterministicStateHash(captured),branch=createBranchAuthority("B-strong",captured,intervention(0,COUNTERFACTUAL_IMPULSE_PRESETS.strong));assert.equal(branch.universe.entities[0].vx,captured.entities[0].vx+.175);assert.equal(deterministicStateHash(primary.continuationState()),hash);});

test("only final effective impulse enters causal identity regardless of presentation multiplication",()=>{const primary=new Universe("multiplier-causal-equivalence"),captured=primary.continuationState(),hash=deterministicStateHash(captured),first=intervention(0,effectiveImpulse(.025,10)),second=intervention(0,effectiveImpulse(.05,5));assert.deepEqual(first,second);assert.equal(interventionHash(first),interventionHash(second));assert.equal(createBranchAuthority("B-1",captured,first).metadata.branchCausalId,createBranchAuthority("B-2",captured,second).metadata.branchCausalId);assert.equal(deterministicStateHash(primary.continuationState()),hash);});

test("Primary Live Trails begin at activation, sample by authoritative ticks, stay bounded, and clear on disable",()=>{const universe=new Universe("primary-live-trails"),recorder=new PrimaryLiveTrailRecorder(4,10);advance(universe,7);recorder.sample(universe);assert.equal(recorder.recordedEntityCount,0);const activationHash=deterministicStateHash(universe.continuationState());recorder.enable(universe);assert.equal(deterministicStateHash(universe.continuationState()),activationHash);assert.equal(recorder.trails()[0].points[0].tick,7);advance(universe,9);recorder.sample(universe);assert.equal(recorder.trails()[0].points.length,1);advance(universe,1);recorder.sample(universe);assert.deepEqual(recorder.trails()[0].points.map((point)=>point.tick),[7,17]);for(let i=0;i<6;i++){advance(universe,10);recorder.sample(universe);}assert.equal(recorder.trails()[0].points.length,4);assert.ok(recorder.stats(0,universe.state.ticks)!.sampledPathLength>=recorder.stats(0,universe.state.ticks)!.displacement);const beforeDisable=deterministicStateHash(universe.continuationState());recorder.disable();assert.equal(recorder.recordedEntityCount,0);assert.equal(deterministicStateHash(universe.continuationState()),beforeDisable);assert.equal(PRIMARY_TRAIL_LIMITS.maximumSamplesPerEntity,64);assert.equal(PRIMARY_TRAIL_LIMITS.maximumRenderedSegments,10_000);});

test("Counterfactual presentation trails cap entities and samples and clear without authority state",()=>{const store=new CounterfactualTrailStore(),make=(tick:number,count=1)=>({branchId:"B",tick,entities:Array.from({length:count},(_,index)=>({localId:index,causalKey:`e${index}`,correspondence:"shared-origin",x:tick+index,y:0,primaryX:index,primaryY:0})),relationships:[]} as unknown as BranchFrame);for(let tick=1;tick<=8;tick++)store.update(make(tick),3);assert.equal(store.sampleCount("e0"),3);store.update(make(9,450),3);assert.equal(store.trackedEntities,400);store.clear();assert.equal(store.trackedEntities,0);});
