import type { Camera } from "../rendering/camera";
import type { Renderer } from "../rendering/renderer";
import { deterministicStateHash } from "../simulation/deterministicStateHash";
import type { Universe } from "../simulation/universe";
import { buildComparisonFrame, type CorrespondenceContext } from "../counterfactual/correspondence";
import { interventionHash, interventionSummary as interventionSummaryText, resolveCanonicalCluster, validateIntervention } from "../counterfactual/intervention";
import { COUNTERFACTUAL_INTERVENTION_VERSION, COUNTERFACTUAL_PROTOCOL_VERSION, type BranchFrame, type BranchMetadata, type CounterfactualIntervention, type DivergenceMetrics, type WorkerCommand, type WorkerResponse } from "../counterfactual/types";
import { CounterfactualTargetGate } from "../counterfactual/scheduling";
import { COUNTERFACTUAL_APPEARANCE_PRESETS, COUNTERFACTUAL_APPEARANCE_STORAGE_KEY, DEFAULT_COUNTERFACTUAL_APPEARANCE, validateCounterfactualAppearance, type CounterfactualAppearance } from "../counterfactual/appearance";
import { COUNTERFACTUAL_POKE_MULTIPLIER_STORAGE_KEY, effectiveImpulse, effectiveImpulseText, validatePokeMultiplier, type CounterfactualPokeMultiplier } from "../counterfactual/pokePresentation";

type ControllerState="NONE"|"CREATING"|"RUNNING"|"PAUSED"|"TERMINATING"|"TERMINATED"|"RESOURCE_LIMITED"|"ERROR";
export interface BranchTombstone { branchId:string;originTick:number;originHash:string;interventionSummary:string;interventionHash:string;finalTick:number;finalDivergence:DivergenceMetrics|null;terminationReason:string; }
const row=(label:string,value:string)=>`<div><dt>${label}</dt><dd>${value}</dd></div>`;

export function bindCounterfactualPanel(options:{getUniverse:()=>Universe;renderer:Renderer;camera:Camera;isPrimaryPlaying:()=>boolean}){
  const panel=document.querySelector<HTMLElement>("#counterfactualPanel")!,createBox=document.querySelector<HTMLElement>("#counterfactualCreate")!,live=document.querySelector<HTMLElement>("#counterfactualLive")!,values=document.querySelector<HTMLElement>("#counterfactualValues")!,message=document.querySelector<HTMLElement>("#counterfactualMessage")!;
  const action=document.querySelector<HTMLButtonElement>("#createCounterfactual")!,target=document.querySelector<HTMLSelectElement>("#counterfactualTarget")!,interventionKind=document.querySelector<HTMLSelectElement>("#counterfactualIntervention")!,direction=document.querySelector<HTMLInputElement>("#counterfactualDirection")!,directionValue=document.querySelector<HTMLElement>("#counterfactualDirectionValue")!,magnitude=document.querySelector<HTMLSelectElement>("#counterfactualMagnitude")!,multiplier=document.querySelector<HTMLSelectElement>("#counterfactualMultiplier")!,preview=document.querySelector<HTMLElement>("#counterfactualPreview")!,confirm=document.querySelector<HTMLButtonElement>("#counterfactualConfirm")!,cancel=document.querySelector<HTMLButtonElement>("#counterfactualCancel")!,pause=document.querySelector<HTMLButtonElement>("#counterfactualPause")!,overlayToggle=document.querySelector<HTMLButtonElement>("#counterfactualOverlayToggle")!,preset=document.querySelector<HTMLSelectElement>("#counterfactualAppearancePreset")!,hue=document.querySelector<HTMLInputElement>("#counterfactualHue")!,opacity=document.querySelector<HTMLInputElement>("#counterfactualOpacity")!,entitySize=document.querySelector<HTMLInputElement>("#counterfactualEntitySize")!,relationshipWeight=document.querySelector<HTMLInputElement>("#counterfactualRelationshipWeight")!,relationshipOpacity=document.querySelector<HTMLInputElement>("#counterfactualRelationshipOpacity")!,connectorOpacity=document.querySelector<HTMLInputElement>("#counterfactualConnectorOpacity")!,haloIntensity=document.querySelector<HTMLInputElement>("#counterfactualHaloIntensity")!,trailOpacity=document.querySelector<HTMLInputElement>("#counterfactualTrailOpacity")!,trailWeight=document.querySelector<HTMLInputElement>("#counterfactualTrailWeight")!,trailSamples=document.querySelector<HTMLInputElement>("#counterfactualTrailSamples")!,trails=document.querySelector<HTMLInputElement>("#counterfactualTrails")!,follow=document.querySelector<HTMLInputElement>("#counterfactualFollow")!,terminateButton=document.querySelector<HTMLButtonElement>("#counterfactualTerminate")!;
  let appearance:CounterfactualAppearance=DEFAULT_COUNTERFACTUAL_APPEARANCE;try{appearance=validateCounterfactualAppearance(JSON.parse(localStorage.getItem(COUNTERFACTUAL_APPEARANCE_STORAGE_KEY)??"null"));}catch{/* Defaults remain available when storage is unavailable. */}
  let pokeMultiplier:CounterfactualPokeMultiplier=1;try{pokeMultiplier=validatePokeMultiplier(localStorage.getItem(COUNTERFACTUAL_POKE_MULTIPLIER_STORAGE_KEY));}catch{/* Default multiplier remains. */}multiplier.value=String(pokeMultiplier);
  let selectedId:number|null=null,selectedRelationshipId:string|null=null,state:ControllerState="NONE",worker:Worker|null=null,metadata:BranchMetadata|null=null,frame:BranchFrame|null=null,context:CorrespondenceContext|null=null,branchCounter=0,lastTargetSent=-1,lastTargetAt=0,lastPanelAt=0,lastMachineCreateAt=-Infinity,overlayVisible=true,tombstone:BranchTombstone|null=null,interventionSummary="",currentIntervention:CounterfactualIntervention|null=null,confirmedMagnitude=0,terminationTimer=0;const targetGate=new CounterfactualTargetGate(),experimentSummaries:unknown[]=[];
  const appearanceControls=[hue,opacity,entitySize,relationshipWeight,relationshipOpacity,connectorOpacity,haloIntensity,trailOpacity,trailWeight,trailSamples];
  function syncAppearanceControls():void{preset.value=appearance.preset;hue.value=String(appearance.hue);opacity.value=String(appearance.overlayOpacity);entitySize.value=String(appearance.entitySize);relationshipWeight.value=String(appearance.relationshipWeight);relationshipOpacity.value=String(appearance.relationshipOpacity);connectorOpacity.value=String(appearance.connectorOpacity);haloIntensity.value=String(appearance.haloIntensity);trailOpacity.value=String(appearance.trailOpacity);trailWeight.value=String(appearance.trailWeight);trailSamples.value=String(appearance.trailSamples);trails.checked=appearance.trailsEnabled;}
  function readAppearance(custom=true):void{appearance=validateCounterfactualAppearance({preset:custom?"custom":preset.value,hue:Number(hue.value),saturation:appearance.saturation,lightness:appearance.lightness,overlayOpacity:Number(opacity.value),entitySize:Number(entitySize.value),relationshipWeight:Number(relationshipWeight.value),relationshipOpacity:Number(relationshipOpacity.value),connectorOpacity:Number(connectorOpacity.value),haloIntensity:Number(haloIntensity.value),trailOpacity:Number(trailOpacity.value),trailWeight:Number(trailWeight.value),trailSamples:Number(trailSamples.value),trailsEnabled:trails.checked});try{localStorage.setItem(COUNTERFACTUAL_APPEARANCE_STORAGE_KEY,JSON.stringify(appearance));}catch{/* Presentation preferences remain session-local. */}if(options.renderer.counterfactualOverlay)options.renderer.counterfactualOverlay.appearance=appearance;}
  syncAppearanceControls();
  const send=(command:WorkerCommand)=>worker?.postMessage(command);
  const syncLabel=():string=>{if(state==="PAUSED")return"PAUSED";if(state==="RESOURCE_LIMITED")return"RESOURCE LIMITED";if(state==="ERROR")return"ERROR";if(!frame)return state;return frame.lag===0?"LOCKSTEP":`CATCHING UP - ${frame.lag.toLocaleString()} ticks`;};
  function render():void{
    panel.hidden=state==="NONE"&&!createBox.hidden?false:state==="NONE";createBox.hidden=state!=="NONE";live.hidden=!metadata;
    if(metadata&&frame){const m=frame.metrics,p=options.renderer.counterfactualProfile;values.innerHTML=[row("Branch ID",metadata.branchId),row("Status",state),row("Origin tick",metadata.originTick.toLocaleString()),row("Intervention",interventionSummary),row("Effective magnitude",confirmedMagnitude.toFixed(3)),row("Branch age",m.branchAge.toLocaleString()),row("Primary tick",options.getUniverse().state.ticks.toLocaleString()),row("Branch tick",frame.tick.toLocaleString()),row("Synchronization",syncLabel()),row("Mean divergence",m.meanPosition.toFixed(3)),row("Max divergence",m.maximumPosition.toFixed(3)),row("Relationship differences",`${m.relationshipTopologyDifference} (${(m.normalizedRelationshipDivergence*100).toFixed(2)}%)`),row("Population delta",m.populationDelta>0?`+${m.populationDelta}`:String(m.populationDelta)),row("Law divergence",m.lawSetEqual?"no":"yes"),row("First divergent event",m.firstDivergentOccurrenceTick===null?"—":`tick ${m.firstDivergentOccurrenceTick.toLocaleString()}`),row("Overlay entities",String(p.entitiesReceived)),row("Overlay relationships",String(p.relationshipsReceived)),row("Visible divergent",String(p.visibleDivergentEntities)),row("Max screen displacement",`${p.maximumScreenDisplacement.toFixed(2)} px`),row("Last overlay frame",p.lastFrameTick<0?"none":p.lastFrameTick.toLocaleString())].join("");}
    pause.textContent=state==="PAUSED"?"Resume Branch":"Pause Branch";overlayToggle.textContent=overlayVisible?"Hide Overlay":"Show Overlay";
  }
  const interventionVector=():[number,number]=>{const angle=Number(direction.value)*Math.PI/180,amount=effectiveImpulse(Number(magnitude.value),pokeMultiplier);return[Math.cos(angle)*amount,Math.sin(angle)*amount];};
  function updatePreview():void{directionValue.textContent=`${direction.value}°`;try{if(interventionKind.value==="sever"){if(!selectedRelationshipId)throw new Error("Select a relationship to sever");preview.textContent=`Preview only · sever relationship ${selectedRelationshipId}\nThe branch bond, lifecycle candidate, and relationship membership will be removed atomically.`;confirm.disabled=false;return;}if(selectedId===null)throw new Error("Select an entity first");const clusterRequired=["expand","compress","spin-clockwise","spin-counterclockwise"].includes(interventionKind.value),members=target.value==="cluster"||clusterRequired?resolveCanonicalCluster(options.getUniverse(),selectedId):[selectedId],label=magnitude.selectedOptions[0]?.textContent?.split(" ")[0]??"Magnitude",gesture=interventionKind.value==="expand"?"Radial preview: outward":interventionKind.value==="compress"?"Radial preview: inward":interventionKind.value.startsWith("spin")?`Circular preview: ${interventionKind.value.endsWith("clockwise")?"clockwise":"counterclockwise"}`:"Directional preview";preview.textContent=`${gesture} · ${members.length} target${members.length===1?"":"s"}: ${members.join(", ")}\n${effectiveImpulseText(label,Number(magnitude.value),pokeMultiplier)}`;confirm.disabled=false;}catch(error){preview.textContent=error instanceof Error?error.message:"Invalid target";confirm.disabled=true;}}
  function showError(error:unknown):void{message.textContent=error instanceof Error?error.message:String(error);}
  const interventionMagnitude=(value:CounterfactualIntervention):number=>value.kind==="entity-impulse"||value.kind==="cluster-impulse"?Math.hypot(value.deltaVelocity.x,value.deltaVelocity.y):value.kind==="entity-displace"||value.kind==="cluster-displace"?Math.hypot(value.deltaPosition.x,value.deltaPosition.y):value.kind==="cluster-radial-pulse"||value.kind==="cluster-spin"?value.magnitude:0;
  function startCanonical(intervention:CounterfactualIntervention,summary:string,effectiveMagnitude:number):{branchId:string;status:string}{
    if(worker||metadata)throw new Error("Terminate the current branch first");const universe=options.getUniverse(),continuation=universe.continuationState(),originHash=deterministicStateHash(continuation);context={originStateHash:originHash,originEntityCount:continuation.entities.length};currentIntervention=structuredClone(intervention);confirmedMagnitude=effectiveMagnitude;interventionSummary=summary;branchCounter++;const branchId=`B-${branchCounter.toString().padStart(4,"0")}`;state="CREATING";panel.hidden=false;createBox.hidden=true;live.hidden=true;message.textContent=`Creating ${branchId}…`;worker=new Worker(new URL("../counterfactual/branchWorker.ts",import.meta.url),{type:"module",name:`ProtoUniverse ${branchId}`});worker.onmessage=onWorkerMessage;worker.onerror=(event)=>disposeWorker(`worker failed: ${event.message}`);send({protocol:COUNTERFACTUAL_PROTOCOL_VERSION,type:"CREATE_BRANCH",branchId,continuation:structuredClone(continuation),intervention});if(deterministicStateHash(universe.continuationState())!==originHash)throw new Error("Primary continuation changed during branch capture");return{branchId,status:state};
  }
  function disposeWorker(reason:string,finalTick=frame?.tick??metadata?.originTick??0,finalMetrics=frame?.metrics??null):void{
    window.clearTimeout(terminationTimer);if(worker){worker.onmessage=null;worker.onerror=null;worker.terminate();worker=null;}
    if(metadata){tombstone={branchId:metadata.branchId,originTick:metadata.originTick,originHash:metadata.originStateHash,interventionSummary,interventionHash:metadata.interventionHash,finalTick,finalDivergence:finalMetrics,terminationReason:reason};experimentSummaries.push({...tombstone,intervention:currentIntervention,branchCausalId:metadata.branchCausalId,duration:finalTick-metadata.originTick,lawDivergence:finalMetrics?!finalMetrics.lawSetEqual:false});if(experimentSummaries.length>20)experimentSummaries.splice(0,experimentSummaries.length-20);}
    options.renderer.counterfactualOverlay=null;options.renderer.clearCounterfactualPresentation();targetGate.reset();metadata=null;frame=null;context=null;follow.checked=false;state="TERMINATED";panel.hidden=false;live.hidden=true;createBox.hidden=true;message.textContent=`Branch terminated · ${reason}${tombstone?` · final tick ${tombstone.finalTick.toLocaleString()}`:""}`;
  }
  function onWorkerMessage(event:MessageEvent<WorkerResponse>):void{const response=event.data;if(!response||response.protocol!==COUNTERFACTUAL_PROTOCOL_VERSION)return;
    if(response.type==="READY"){metadata=response.metadata;frame=response.frame;targetGate.markFrameReceived();state="RUNNING";message.textContent=`Ready · reconstructed in ${response.reconstructionDurationMs.toFixed(1)} ms`;if(overlayVisible)options.renderer.counterfactualOverlay={frame,appearance};render();return;}
    if(response.type==="FRAME"||response.type==="RESOURCE_LIMIT"){frame=response.frame;targetGate.markFrameReceived();if(response.type==="RESOURCE_LIMIT"){state="RESOURCE_LIMITED";message.textContent=response.reason;}if(overlayVisible)options.renderer.counterfactualOverlay={frame,appearance};if(follow.checked){const diverged=[...frame.entities].filter((x)=>x.primaryX!==null&&x.primaryY!==null).sort((a,b)=>Math.hypot((b.primaryX??b.x)-b.x,(b.primaryY??b.y)-b.y)-Math.hypot((a.primaryX??a.x)-a.x,(a.primaryY??a.y)-a.y))[0];if(diverged){options.camera.x=(diverged.x+diverged.primaryX!)/2;options.camera.y=(diverged.y+diverged.primaryY!)/2;}}render();return;}
    if(response.type==="STATUS"){state=response.status==="PAUSED"?"PAUSED":response.status;if(frame)frame={...frame,tick:response.tick,lag:response.lag};render();return;}
    if(response.type==="ERROR"){if(!metadata){disposeWorker(`creation failed: ${response.message}`);return;}state="ERROR";message.textContent=`${response.code}: ${response.message}`;render();return;}
    if(response.type==="TERMINATED")disposeWorker(response.reason,response.finalTick,response.finalMetrics);
  }
  action.addEventListener("click",()=>{if(state!=="NONE"&&state!=="TERMINATED"){showError("Terminate the active branch before creating another");return;}state="NONE";panel.hidden=false;createBox.hidden=false;live.hidden=true;message.textContent="";updatePreview();});
  for(const control of [target,interventionKind,direction,magnitude])control.addEventListener("input",updatePreview);
  multiplier.addEventListener("change",()=>{pokeMultiplier=validatePokeMultiplier(multiplier.value);try{localStorage.setItem(COUNTERFACTUAL_POKE_MULTIPLIER_STORAGE_KEY,String(pokeMultiplier));}catch{/* Session preference remains active. */}updatePreview();});
  cancel.addEventListener("click",()=>{createBox.hidden=true;panel.hidden=true;});
  confirm.addEventListener("click",()=>{try{const universe=options.getUniverse(),[x,y]=interventionVector();
      const amount=effectiveImpulse(Number(magnitude.value),pokeMultiplier),clusterRequired=["expand","compress","spin-clockwise","spin-counterclockwise"].includes(interventionKind.value);let intervention:CounterfactualIntervention;
      if(interventionKind.value==="sever"){if(!selectedRelationshipId)throw new Error("Select a relationship first");intervention={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"relationship-sever",target:{relationshipId:selectedRelationshipId}};}
      else{if(selectedId===null)throw new Error("Select an entity first");const members=target.value==="cluster"||clusterRequired?resolveCanonicalCluster(universe,selectedId):null;if(interventionKind.value==="displace")intervention=members?{schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"cluster-displace",target:{anchorEntityId:selectedId,resolvedEntityIds:members},deltaPosition:{x,y}}:{schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"entity-displace",target:{entityId:selectedId},deltaPosition:{x,y}};else if(interventionKind.value==="expand"||interventionKind.value==="compress")intervention={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"cluster-radial-pulse",target:{anchorEntityId:selectedId,resolvedEntityIds:members!},mode:interventionKind.value,magnitude:amount};else if(interventionKind.value==="spin-clockwise"||interventionKind.value==="spin-counterclockwise")intervention={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"cluster-spin",target:{anchorEntityId:selectedId,resolvedEntityIds:members!},direction:interventionKind.value==="spin-clockwise"?"clockwise":"counterclockwise",magnitude:amount};else intervention=members?{schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"cluster-impulse",target:{anchorEntityId:selectedId,resolvedEntityIds:members},deltaVelocity:{x,y}}:{schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"entity-impulse",target:{entityId:selectedId},deltaVelocity:{x,y}};}
      startCanonical(intervention,`${intervention.kind} ${intervention.kind==="relationship-sever"?selectedRelationshipId:`${Number(magnitude.value).toFixed(3)} × ${pokeMultiplier}`}`,intervention.kind==="relationship-sever"?0:amount);interventionHash(intervention);
    }catch(error){showError(error);if(worker)disposeWorker("creation failed");}});
  pause.addEventListener("click",()=>{if(!worker)return;if(state==="PAUSED"){state="RUNNING";send({protocol:COUNTERFACTUAL_PROTOCOL_VERSION,type:"RESUME"});}else if(state==="RUNNING"){state="PAUSED";send({protocol:COUNTERFACTUAL_PROTOCOL_VERSION,type:"PAUSE"});}render();});
  overlayToggle.addEventListener("click",()=>{overlayVisible=!overlayVisible;options.renderer.counterfactualOverlay=overlayVisible&&frame?{frame,appearance}:null;render();});
  preset.addEventListener("change",()=>{if(preset.value!=="custom"){const colors=COUNTERFACTUAL_APPEARANCE_PRESETS[preset.value as keyof typeof COUNTERFACTUAL_APPEARANCE_PRESETS];appearance={...appearance,preset:preset.value as CounterfactualAppearance["preset"],...colors};syncAppearanceControls();readAppearance(false);}else readAppearance(false);});
  for(const control of appearanceControls)control.addEventListener("input",()=>readAppearance(true));
  trails.addEventListener("change",()=>{readAppearance(true);if(!trails.checked)options.renderer.clearCounterfactualTrails();});
  terminateButton.addEventListener("click",()=>{if(!worker){disposeWorker("user terminated");return;}state="TERMINATING";send({protocol:COUNTERFACTUAL_PROTOCOL_VERSION,type:"TERMINATE",reason:"user terminated"});terminationTimer=window.setTimeout(()=>disposeWorker("user terminated"),100);render();});
  return{
    selectEntity(id:number|null){selectedId=id;if(id!==null){selectedRelationshipId=null;interventionKind.value="poke";}action.hidden=id===null&&selectedRelationshipId===null;action.disabled=action.hidden;createBox.hidden=true;updatePreview();},
    selectRelationship(id:string|null){selectedRelationshipId=id;if(id!==null){selectedId=null;interventionKind.value="sever";}action.hidden=id===null&&selectedId===null;action.disabled=action.hidden;createBox.hidden=true;updatePreview();},
    machineCreate(args:unknown){
      if(performance.now()-lastMachineCreateAt<500)throw new Error("Counterfactual create rate limit: wait 500 ms");lastMachineCreateAt=performance.now();
      if(!args||typeof args!=="object"||Array.isArray(args))throw new Error("Invalid counterfactual create request");
      const value=args as Record<string,unknown>,allowed=new Set(["kind","entityId","relationshipId","x","y","magnitude"]);for(const key of Object.keys(value))if(!allowed.has(key))throw new Error(`Unsupported field: ${key}`);
      const kind=String(value.kind??""),entityId=Number(value.entityId),relationshipId=String(value.relationshipId??""),x=Number(value.x),y=Number(value.y),amount=Number(value.magnitude),universe=options.getUniverse();let intervention:CounterfactualIntervention;
      if(kind==="relationship-sever")intervention={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind,target:{relationshipId}};
      else if(kind==="entity-impulse")intervention={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind,target:{entityId},deltaVelocity:{x,y}};
      else if(kind==="entity-displace")intervention={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind,target:{entityId},deltaPosition:{x,y}};
      else{const members=resolveCanonicalCluster(universe,entityId);if(kind==="cluster-impulse")intervention={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind,target:{anchorEntityId:entityId,resolvedEntityIds:members},deltaVelocity:{x,y}};else if(kind==="cluster-displace")intervention={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind,target:{anchorEntityId:entityId,resolvedEntityIds:members},deltaPosition:{x,y}};else if(kind==="cluster-expand"||kind==="cluster-compress")intervention={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"cluster-radial-pulse",target:{anchorEntityId:entityId,resolvedEntityIds:members},mode:kind==="cluster-expand"?"expand":"compress",magnitude:amount};else if(kind==="cluster-spin-clockwise"||kind==="cluster-spin-counterclockwise")intervention={schemaVersion:COUNTERFACTUAL_INTERVENTION_VERSION,kind:"cluster-spin",target:{anchorEntityId:entityId,resolvedEntityIds:members},direction:kind==="cluster-spin-clockwise"?"clockwise":"counterclockwise",magnitude:amount};else throw new Error("Unsupported intervention kind");}
      const validated=validateIntervention(intervention,universe);return startCanonical(validated,interventionSummaryText(validated),interventionMagnitude(validated));
    },
    machineStatus(){return{state,metadata,frame:frame&&{tick:frame.tick,lag:frame.lag,status:frame.status,metrics:frame.metrics},summaries:[...experimentSummaries]};},
    machineCompare(args:{entityId?:number;relationshipId?:string}){if(!frame)throw new Error("No branch frame available");const selected=args.entityId!==undefined?frame.entities.filter(item=>item.localId===args.entityId).slice(0,1):args.relationshipId!==undefined?frame.relationships.filter(item=>item.causalKey===args.relationshipId).slice(0,1):undefined;return{branchId:frame.branchId,tick:frame.tick,branchStateHash:frame.branchStateHash,metrics:frame.metrics,selected};},
    machineInspect(args:{entityId?:number;relationshipId?:string}){if(!frame)throw new Error("No branch frame available");if(args.entityId!==undefined)return frame.entities.filter((item)=>item.localId===args.entityId).slice(0,1);if(args.relationshipId!==undefined)return frame.relationships.filter((item)=>item.causalKey===args.relationshipId).slice(0,1);return{entities:frame.entities.slice(0,25),relationships:frame.relationships.slice(0,25)};},
    machineTerminate(){if(!worker)throw new Error("No active branch");state="TERMINATING";send({protocol:COUNTERFACTUAL_PROTOCOL_VERSION,type:"TERMINATE",reason:"machine terminated"});terminationTimer=window.setTimeout(()=>disposeWorker("machine terminated"),100);return{status:"TERMINATING"};},
    update(){const now=performance.now();if(metadata&&now-lastPanelAt>=250){lastPanelAt=now;render();}if(!worker||!metadata||!context||state!=="RUNNING"||!options.isPrimaryPlaying()||!targetGate.canPublish())return;const universe=options.getUniverse();if(universe.state.ticks===lastTargetSent||now-lastTargetAt<100)return;const primary=buildComparisonFrame(universe,context);lastTargetSent=primary.tick;lastTargetAt=now;targetGate.markPublished();send({protocol:COUNTERFACTUAL_PROTOCOL_VERSION,type:"SET_TARGET_TICK",targetTick:primary.tick,primary});},
    terminate(reason="primary session changed"){if(worker){state="TERMINATING";send({protocol:COUNTERFACTUAL_PROTOCOL_VERSION,type:"TERMINATE",reason});terminationTimer=window.setTimeout(()=>disposeWorker(reason),100);}else if(metadata)disposeWorker(reason);},
    get state(){return state;},get tombstone(){return tombstone;}
  };
}
